/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-07-23 09:14:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>Contact</title>\r\n");
      out.write("  <meta content=\"\" name=\"descriptison\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/owl.carousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: Sailor - v2.0.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/sailor-free-bootstrap-theme/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("  <!-- ======= Header ======= -->\r\n");
      out.write("  <header id=\"header\" class=\"fixed-top \">\r\n");
      out.write("    <div class=\"container d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("  <h1 class=\"logo\"><a href=\"index.jsp\" style=\"color:skyblue;font-size: calc(0.5em + 0.5vw)\" ><img src=\"assets/img/bg/CA.png\" style=\"width: 80px;padding-right: 20px\"></a>\r\n");
      out.write("      </h1>\r\n");
      out.write("       <h1 class=\"logo \"><a href=\"index.jsp\" style=\"color:skyblue;font-size:calc(0.5em + 0.5vw)\" >Pusegaonkar & Dindokar <br><label style=\"color: black\">Chartered Accountants</label></a>\r\n");
      out.write("      </h1>\r\n");
      out.write("      <!--       <h1 class=\"logo\" style=\"opacity: 0\"><a href=\"index.jsp\" style=\"color:skyblue;font-size: 20px\" >Pusegaonkar</a>\r\n");
      out.write("      </h1>\r\n");
      out.write("      <br><h1 class=\"logo\"><a href=\"index.jsp\" style=\"font-size: 18px;opacity: 0\" >.</a></h1> -->\r\n");
      out.write("      <!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("      <!-- <a href=\"index.jsp\" class=\"logo\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"nav-menu d-none d-lg-block ml-auto\">\r\n");
      out.write("\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li ><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\r\n");
      out.write("          <li class=\"drop-down\"><a href=\"#\">About</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("              <li><a href=\"partners.html\">Partners</a></li>\r\n");
      out.write("              <li><a href=\"Clientele.html\">Clientele</a></li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li><a href=\"services.html\">Services</a></li>\r\n");
      out.write("          <li class=\"drop-down\"><a href=\"#\">Blog</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                  <li><a href=\"VideoBlog.jsp\">Video Blogs</a></li>\r\n");
      out.write("                  <li><a href=\"photo_blog.jsp\">Photo Blogs</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li><a href=\"Link&Update.jsp\">Links & Updates</a></li>\r\n");
      out.write("\r\n");
      out.write("          <li class=\"active\"><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("       \r\n");
      out.write("            \r\n");
      out.write("                \r\n");
      out.write("                  <li> <a href=\"admin.html\">Admin</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("      </nav><!-- .nav-menu -->\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </header><!-- End Header -->\r\n");
      out.write("  <main id=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ======= Breadcrumbs ======= -->\r\n");
      out.write("    <section id=\"breadcrumbs\" class=\"breadcrumbs\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("          <h2>Contact</h2>\r\n");
      out.write("          <ol>\r\n");
      out.write("            <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("            <li>Contact</li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End Breadcrumbs -->\r\n");
      out.write("\r\n");
      out.write("    <!-- ======= Team Section ======= -->\r\n");
      out.write("    <section id=\"team\" class=\"team section-bg\" >\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write(" <section id=\"blog\" class=\"blog contact\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4  col-md-6 d-flex align-items-stretch\" data-aos=\"fade-up\">\r\n");
      out.write("            <article class=\"entry\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"entry-img\">\r\n");
      out.write("\r\n");
      out.write("                <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3782.398311887615!2d73.79063531417492!3d18.55607298738831!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bed859a97c19%3A0x967e5bb6fda7cbcf!2sBana%20Pvt%20Ltd!5e0!3m2!1sen!2sin!4v1592801239950!5m2!1sen!2sin\" width=\"100%\" height=\"180px\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\" aria-hidden=\"false\" tabindex=\"0\"></iframe>\r\n");
      out.write("                \r\n");
      out.write("               <!--  <img src=\"assets/img/team/team-1.jpg\" alt=\"\" class=\"img-fluid\"> -->\r\n");
      out.write("              </div>\r\n");
      out.write("   \r\n");
      out.write("                 <div class=\"info\">\r\n");
      out.write("              <div class=\"address\">\r\n");
      out.write("                <a href=\"https://www.google.co.in/maps/place/Bana+Pvt+Ltd/@18.556073,73.7906353,17z/data=!3m1!4b1!4m5!3m4!1s0x3bc2bed859a97c19:0x967e5bb6fda7cbcf!8m2!3d18.556073!4d73.792824\"><i class=\"icofont-google-map\"></i></a>\r\n");
      out.write("                <h4>Pune Location:</h4>\r\n");
      out.write("                <h6><p>208,Amar Neptune baner Pune 411045</p></h6>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"email\">\r\n");
      out.write("                <i class=\"icofont-envelope\"></i>\r\n");
      out.write("                <h4>Email:</h4>\r\n");
      out.write("                <p>info@pandd.in</p>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"phone\">\r\n");
      out.write("                <i class=\"icofont-phone\"></i>\r\n");
      out.write("                <h4>Call:</h4>\r\n");
      out.write("                <p>+91 98347 42691</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("            </article><!-- End blog entry -->\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4  col-md-6 d-flex align-items-stretch\" data-aos=\"fade-up\" > \r\n");
      out.write("            \r\n");
      out.write("            <article class=\"entry\">\r\n");
      out.write("  <div class=\"entry-img\">\r\n");
      out.write("               <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3783.434732244702!2d73.81032861418548!3d18.509246687415576!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2bfbbf878c433%3A0x47e0ef9e9e2a0fbc!2sVidya%20Sahakari%20Bank%20Limited%20-%20Paud%20Road!5e0!3m2!1sen!2sin!4v1591937199241!5m2!1sen!2sin\" width=\"100%\" height=\"180px\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\" aria-hidden=\"false\" tabindex=\"0\"></iframe>\r\n");
      out.write("               <!--  <img src=\"assets/img/team/team-1.jpg\" alt=\"\" class=\"img-fluid\"> -->\r\n");
      out.write("              </div>\r\n");
      out.write("                \r\n");
      out.write("                 <div class=\"info\">\r\n");
      out.write("              <div class=\"address\">\r\n");
      out.write("                <a href=\"https://www.google.com/maps/place/Vidya+Sahakari+Bank+Limited+-+Paud+Road/@18.5092467,73.8103286,17z/data=!3m1!4b1!4m5!3m4!1s0x3bc2bfbbf878c433:0x47e0ef9e9e2a0fbc!8m2!3d18.5092467!4d73.8125173\"><i class=\"icofont-google-map\"></i></a>\r\n");
      out.write("                <h4>Pirangut Location:</h4>\r\n");
      out.write("                <h6><p>UG-45, oxford avenye,near vidya sahakari bank, lavale phata, pirangut,pune-412115 </p></h6>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"email\">\r\n");
      out.write("                <i class=\"icofont-envelope\"></i>\r\n");
      out.write("                <h4>Email:</h4>\r\n");
      out.write("                <p>info@pandd.in</p>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"phone\">\r\n");
      out.write("                <i class=\"icofont-phone\"></i>\r\n");
      out.write("                <h4>Call:</h4>\r\n");
      out.write("                <p>+91 9765265588</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4  col-md-6 d-flex align-items-stretch\" data-aos=\"fade-up\">\r\n");
      out.write("            <article class=\"entry\">\r\n");
      out.write("\r\n");
      out.write("             <div class=\"entry-img\">\r\n");
      out.write("               <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3780.049698456376!2d73.77187181418842!3d18.66176568732686!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bc2b9e92a3d0001%3A0x1668fa0584d94681!2sControl%20and%20Automation%20Systems!5e0!3m2!1sen!2sin!4v1591936173830!5m2!1sen!2sin\" width=\"100%\" height=\"180px\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\" aria-hidden=\"false\" tabindex=\"0\"></iframe>\r\n");
      out.write("               <!--  <img src=\"assets/img/team/team-1.jpg\" alt=\"\" class=\"img-fluid\"> -->\r\n");
      out.write("              </div>\r\n");
      out.write("                \r\n");
      out.write("                 <div class=\"info\">\r\n");
      out.write("              <div class=\"address\">\r\n");
      out.write("                <a href=\"https://www.google.com/maps/place/Control+and+Automation+Systems/@18.6617657,73.7718718,17z/data=!3m1!4b1!4m5!3m4!1s0x3bc2b9e92a3d0001:0x1668fa0584d94681!8m2!3d18.6617657!4d73.7740605\"><i class=\"icofont-google-map\"></i></a>\r\n");
      out.write("                <h4>Nigdi Location:</h4>\r\n");
      out.write("                <h6><p>Pasaydan, Plot No. 72 , Sec No. 24 , PCNTDA , Nigdi , Pune â 411044. </p></h6>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"email\">\r\n");
      out.write("                <i class=\"icofont-envelope\"></i>\r\n");
      out.write("                <h4>Email:</h4>\r\n");
      out.write("                <p>info@pandd.in</p>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"phone\">\r\n");
      out.write("                <i class=\"icofont-phone\"></i>\r\n");
      out.write("                <h4>Call:</h4>\r\n");
      out.write("                <p>+91 9881439237</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </article><!-- End blog entry -->\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-lg-4  col-md-6 d-flex align-items-stretch\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("            </article><!-- End blog entry -->\r\n");
      out.write("\r\n");
      out.write("            <article class=\"entry\">\r\n");
      out.write("\r\n");
      out.write("             <div class=\"entry-img\">\r\n");
      out.write("               <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1903.615369369841!2d74.09537565787008!3d17.400710997017654!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTfCsDI0JzAyLjYiTiA3NMKwMDUnNDcuMyJF!5e0!3m2!1sen!2sin!4v1591940093752!5m2!1sen!2sin\" width=\"100%\" height=\"180px\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\" aria-hidden=\"false\" tabindex=\"0\"></iframe>\r\n");
      out.write("               <!--  <img src=\"assets/img/team/team-1.jpg\" alt=\"\" class=\"img-fluid\"> -->\r\n");
      out.write("              </div>\r\n");
      out.write("                \r\n");
      out.write("                 <div class=\"info\">\r\n");
      out.write("              <div class=\"address\">\r\n");
      out.write("                <a href=\"https://www.google.com/maps/place/17%C2%B024'02.6%22N+74%C2%B005'47.3%22E/@17.400711,74.0953757,18z/data=!3m1!4b1!4m6!3m5!1s0x0:0x0!7e2!8m2!3d17.4007106!4d74.0964696\"><i class=\"icofont-google-map\"></i></a>\r\n");
      out.write("                <h4> Satara Location:</h4>\r\n");
      out.write("                <h6><p>Flat no 01, Padma residency,  Collage Road,  Malinagar,  Umbraj 415109</p></h6>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"email\">\r\n");
      out.write("                <i class=\"icofont-envelope\"></i>\r\n");
      out.write("                <h4>Email:</h4>\r\n");
      out.write("                <p>info@pandd.in</p>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"phone\">\r\n");
      out.write("                <i class=\"icofont-phone\"></i>\r\n");
      out.write("                <h4>Call:</h4>\r\n");
      out.write("                <p>+91  77093 00663</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </article><!-- End blog entry -->            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4  col-md-6 d-flex align-items-stretch\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </article><!-- End blog entry -->\r\n");
      out.write("            <article class=\"entry\">\r\n");
      out.write("\r\n");
      out.write("               <div class=\"entry-img\">\r\n");
      out.write("                <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3770.3517469597673!2d74.7217753141967!3d19.092218887078644!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bdcb08c4d9247d5%3A0x8d3c27c23fada2cb!2sNagar-Kalyan%20Rd%2C%20Samata%20Nagar%2C%20Ahmednagar%2C%20Maharashtra%20414001!5e0!3m2!1sen!2sin!4v1591935597796!5m2!1sen!2sin\" width=\"100%\" height=\"180px\" frameborder=\"0\" style=\"border:0;\" allowfullscreen=\"\" aria-hidden=\"false\" tabindex=\"0\"></iframe>\r\n");
      out.write("               \r\n");
      out.write("               <!--  <img src=\"assets/img/team/team-1.jpg\" alt=\"\" class=\"img-fluid\"> -->\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("                 <div class=\"info\">\r\n");
      out.write("              <div class=\"address\">\r\n");
      out.write("                <a href=\"https://www.google.co.in/maps/place/Nagar-Kalyan+Rd,+Samata+Nagar,+Ahmednagar,+Maharashtra+414001/@19.0922189,74.7217753,17z/data=!4m8!1m2!2m1!1sPlot+no+40,+Riya+park,+shivaji+Nagar,+Kalyan+road,+Ahmednagar!3m4!1s0x3bdcb08c4d9247d5:0x8d3c27c23fada2cb!8m2!3d19.0922192!4d74.723964\"><i class=\"icofont-google-map\"></i></a>\r\n");
      out.write("                <h4>Ahmednagar Location:</h4>\r\n");
      out.write("                <h6><p>Plot no 40, Riya park, shivaji Nagar, Kalyan road, Ahmednagar</p></h6>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"email\">\r\n");
      out.write("                <i class=\"icofont-envelope\"></i>\r\n");
      out.write("                <h4>Email:</h4>\r\n");
      out.write("                <p>info@pandd.in</p>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"phone\">\r\n");
      out.write("                <i class=\"icofont-phone\"></i>\r\n");
      out.write("                <h4>Call:</h4>\r\n");
      out.write("                <p>+91 94214 35786</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4  col-md-6 d-flex align-items-stretch\" data-aos=\"fade-up\">\r\n");
      out.write("            <article class=\"entry\" style=\"background-color:lightgray;\">\r\n");
      out.write("              <h3 style=\"text-align: center;color:crimson\">Contact Us</h3>\r\n");
      out.write("\r\n");
      out.write("                <form style=\"padding-top: 20px;background-color:lightgray;\" action=\"email.jsp\" method=\"post\" role=\"form\">\r\n");
      out.write("              <div class=\"form-row\">\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <input type=\"text\" name=\"name\" class=\"form-control\" required style=\"border:inset;\" id=\"name\" placeholder=\"Your Name\" data-rule=\"minlen:4\" data-msg=\"Please enter at least 4 chars\" />\r\n");
      out.write("                  <div class=\"validate\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 form-group\">\r\n");
      out.write("                  <input type=\"email\" class=\"form-control\" name=\"email\" required id=\"email\" style=\"border:inset;\" placeholder=\"Your Email\" data-rule=\"email\" data-msg=\"Please enter a valid email\" />\r\n");
      out.write("                  <div class=\"validate\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" required name=\"subject\" id=\"subject\"  style=\"border:inset;\" placeholder=\"Subject\" data-rule=\"minlen:4\" data-msg=\"Please enter at least 8 chars of subject\" />\r\n");
      out.write("                <div class=\"validate\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" required class=\"form-control\" name=\"contactNo\" id=\"conactNo\"  style=\"border:inset;\" placeholder=\"Contact No.\" data-rule=\"minlen:4\" data-msg=\"Please enter at least 8 chars of subject\" />\r\n");
      out.write("                <div class=\"validate\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <textarea class=\"form-control\" name=\"message\" required rows=\"5\" style=\"border:inset;\"  data-rule=\"required\" data-msg=\"Please write something for us\" placeholder=\"Message\"></textarea>\r\n");
      out.write("                <div class=\"validate\"></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"text-center\"><button type=\"submit\" class=\"button1\">Send Message</button></div>\r\n");
      out.write("            </form>\r\n");
      out.write("<!-- \r\n");
      out.write("              <div class=\"entry-img\">\r\n");
      out.write("                <img src=\"assets/img/blog-6.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <h2 class=\"entry-title\">\r\n");
      out.write("                <a href=\"blog-single.html\">Debitis cupiditate saepe ex quam aut id. Consequatur dignissimos et id id.</a>\r\n");
      out.write("              </h2>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"entry-meta\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                  <li class=\"d-flex align-items-center\"><i class=\"icofont-user\"></i> <a href=\"blog-single.html\">John Doe</a></li>\r\n");
      out.write("                  <li class=\"d-flex align-items-center\"><i class=\"icofont-wall-clock\"></i> <a href=\"blog-single.html\"><time datetime=\"2020-01-01\">Jan 1, 2020</time></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"entry-content\">\r\n");
      out.write("                <p>\r\n");
      out.write("                  Modi dolor et placeat ut iure ad. Qui perferendis fugit quo et cumque facilis et debitis rerum. Repellendus animi qui eos. Unde perferendis et tempora Ratione porro omnis magn delata sera marto ned.\r\n");
      out.write("                </p>\r\n");
      out.write("                <div class=\"read-more\">\r\n");
      out.write("                  <a href=\"blog-single.html\">Read More</a>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div> -->\r\n");
      out.write("\r\n");
      out.write("            </article><!-- End blog entry -->\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End Blog Section -->\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End Team Section -->\r\n");
      out.write("\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("  <!-- ======= Footer ======= -->\r\n");
      out.write("  <footer id=\"footer\">\r\n");
      out.write("    <div class=\"footer-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("            <div class=\"footer-info\">\r\n");
      out.write("              <h3><a href=\"index.jsp\" style=\"color:skyblue;font-size: 20px\" >Pusegaonkar & Dindokar</a>\r\n");
      out.write("      <label style=\"font-size: 18px;\">  Chartered Accountants</label></h3>\r\n");
      out.write("              <p>\r\n");
      out.write("                208,Amar Neptune baner Pune 411045 <br>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <strong>Phone:</strong>+91 9834742691<br>\r\n");
      out.write("                <strong>Email:</strong> info@pandd.in<br>\r\n");
      out.write("              </p>\r\n");
      out.write("              <div class=\"social-links mt-3\">\r\n");
      out.write("                <a href=\"https://twitter.com/CAPANDD\" class=\"twitter\"><i class=\"bx bxl-twitter\"></i></a>\r\n");
      out.write("                <a href=\"https://www.facebook.com/capandd\" class=\"facebook\"><i class=\"bx bxl-facebook\"></i></a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"https://www.youtube.com/channel/UCzmlQfqLNmY9PI2lMabuaVA\" class=\"google-plus\"><i class=\"bx bxl-youtube\"></i></a>\r\n");
      out.write("                <a href=\"https://www.linkedin.com/company/54317819\" class=\"linkedin\"><i class=\"bx bxl-linkedin\"></i></a>\r\n");
      out.write("                <a href=\"https://wa.me/919834742691?text=I%20would%20like%20to%20have%20your%20servies\" class=\"google-plus\"><i class=\"bx bxl-whatsapp\"></i></a>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"https://t.me/PUSEGAONKARANDDINDOKAR\" class=\"google-plus\" style=\"margin-top: 5px\"><i class=\"bx bxl-telegram\"></i></a>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-2 col-md-6 footer-links\">\r\n");
      out.write("            <h4>Useful Links</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"about.html\">About us</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Services</a></li>\r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("             <li><i class=\"bx bx-chevron-right\"></i><a href=\"VideoBlog.jsp\">Video Blogs</a></li>\r\n");
      out.write("            <li><i class=\"bx bx-chevron-right\"></i><a href=\"photo_blog.jsp\">Photo Blogs</a></li>\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"#\">Links & Updates</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-3 col-md-6 footer-links\">\r\n");
      out.write("            <h4>Our Services</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Audit & Assurance</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Direct & Indirect Taxes</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Banking & Finance</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Business and Knowledge Process Outsourcing and Accounting</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Corporate Law</a></li>\r\n");
      out.write("             \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 footer-newsletter\">\r\n");
      out.write("            <h4><a href=\"https://www.youtube.com/channel/UCzmlQfqLNmY9PI2lMabuaVA\">Our Youtube Channel</a></h4>\r\n");
      out.write("            <p></p>\r\n");
      out.write("            <form action=\"\" method=\"post\">\r\n");
      out.write("              <a href=\"https://www.youtube.com/channel/UCzmlQfqLNmY9PI2lMabuaVA\"><input type=\"email\" name=\"email\"><input type=\"submit\" value=\"Subscribe\"></a>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </footer><!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/venobox/venobox.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
