/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.36
 * Generated at: 2020-07-23 09:16:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Photo;
import java.util.*;

public final class photo_005ftable_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Photo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>Photo Table</title>\r\n");
      out.write("  <meta content=\"\" name=\"descriptison\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/icofont/icofont.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/animate.css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/venobox/venobox.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/owl.carousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: Sailor - v2.0.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/sailor-free-bootstrap-theme/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Header ======= -->\r\n");
      out.write("  <header id=\"header\" class=\"fixed-top \">\r\n");
      out.write("    <div class=\"container d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("     <h1 class=\"logo\"><a href=\"index.jsp\" style=\"color:skyblue;font-size: calc(0.5em + 0.5vw)\" ><img src=\"assets/img/bg/CA.png\" style=\"width: 80px;padding-right: 20px\"></a>\r\n");
      out.write("      </h1>\r\n");
      out.write("       <h1 class=\"logo \"><a href=\"index.jsp\" style=\"color:skyblue;font-size:calc(0.5em + 0.5vw)\" >Pusegaonkar & Dindokar <br><label style=\"color: black\">Chartered Accountants</label></a>\r\n");
      out.write("      </h1>\r\n");
      out.write("<!--       <h1 class=\"logo\" style=\"opacity: 0\"><a href=\"index.jsp\" style=\"color:skyblue;font-size: 20px\" >Pusegaonkar</a>\r\n");
      out.write("      </h1>\r\n");
      out.write("      <br><h1 class=\"logo\"><a href=\"index.jsp\" style=\"font-size: 18px;opacity: 0\" >.</a></h1> -->\r\n");
      out.write("      <!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("      <!-- <a href=\"index.jsp\" class=\"logo\"><img src=\"assets/img/logo.png\" alt=\"\" class=\"img-fluid\"></a>-->\r\n");
      out.write("\r\n");
      out.write("      <nav class=\"nav-menu d-none d-lg-block ml-auto\">\r\n");
      out.write("\r\n");
      out.write("        <ul>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("          <li class=\"drop-down active\"><a href=\"#\">Tables</a>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><a href=\"link_table.jsp\">Link_Table</a></li>\r\n");
      out.write("              <li><a href=\"update_table.jsp\">Update_Table</a></li>\r\n");
      out.write("              <li><a href=\"video_table.jsp\">Video_Table</a></li>\r\n");
      out.write("               <li><a href=\"photo_table.jsp\">Photo_Table</a></li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li ><a href=\"upload.html\">Upload</a></li>\r\n");
      out.write("          \r\n");
      out.write("          <li> <a href=\"index.jsp\">Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("      </nav><!-- .nav-menu -->\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </header><!-- End Header -->\r\n");
      out.write("\r\n");
      out.write("  <main id=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <!-- ======= Breadcrumbs ======= -->\r\n");
      out.write("    <section id=\"breadcrumbs\" class=\"breadcrumbs\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("          <h2>Photo Table</h2>\r\n");
      out.write("          <ol>\r\n");
      out.write("            <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("            <li>Photo Table</li>\r\n");
      out.write("          </ol>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End Breadcrumbs -->\r\n");
      out.write("\r\n");
      out.write("        <!-- %&&&&%$^$W%^#$^#$ -->\r\n");
      out.write("\r\n");
      out.write("        <!-- ======= Pricing Section ======= -->\r\n");
      out.write("    <section id=\"pricing\" class=\"pricing\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         ");

         Photo photoObj=Photo.getPhotoObj();
         List<List<String>> PhotoDbList=photoObj.getPhotoDbOutterList();
         if(PhotoDbList != null)
         {
         System.out.println("asdsdsadsadas");
         System.out.println(PhotoDbList);  
         
         }
         
        
         
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"table-responsive\">\r\n");
      out.write("  <table class=\"table table-dark\">\r\n");
      out.write("    <thead>\r\n");
      out.write("      <tr>\r\n");
      out.write("    <th>ID</th>\r\n");
      out.write("    <th>Photo Heading</th>\r\n");
      out.write("    <th >Description</th>\r\n");
      out.write("    <th >Folder Name</th>\r\n");
      out.write("    <th >Date</th>\r\n");
      out.write("    <th >Delete</th>\r\n");
      out.write("  </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody>\r\n");
      out.write("        ");
  for(List<String> innerList : PhotoDbList)
  {  System.out.println("Splitting====>");
   System.out.println(innerList);
   String[] myArray = new String[innerList.size()];
   innerList.toArray(myArray);
   
   

  
  for(int i=0;i<1;i++)
   {
      out.write("\r\n");
      out.write("\r\n");
      out.write("     <tr>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <td >");
      out.print(myArray[0]);
      out.write("</td>\r\n");
      out.write("    <td >");
      out.print(myArray[1]);
      out.write("</td>\r\n");
      out.write("    <td >");
      out.print(myArray[2]);
      out.write("</td>\r\n");
      out.write("    <td >");
      out.print(myArray[3]);
      out.write("</td>\r\n");
      out.write("    <td >");
      out.print(myArray[4]);
      out.write("</td>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <td ><a href=\"Delete.jsp?id=");
      out.print(myArray[0]);
      out.write("&folderName=");
      out.print(myArray[3]);
      out.write("&table=");
      out.print("photo");
      out.write("\"><button type=\"button\" class=\"button2\">Delete</button></a></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  ");

   }} 
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </section><!-- End Pricing Section -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- %&&&&%$^$W%^#$^#$ -->\r\n");
      out.write("\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("  <!-- ======= Footer ======= -->\r\n");
      out.write("  <footer id=\"footer\">\r\n");
      out.write("    <div class=\"footer-top\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("            <div class=\"footer-info\">\r\n");
      out.write("              <h3><a href=\"index.jsp\" style=\"color:skyblue;font-size: 20px\" >Pusegaonkar & Dindokar</a>\r\n");
      out.write("      <label style=\"font-size: 18px;\">  Chartered Accountants</label></h3>\r\n");
      out.write("              <p>\r\n");
      out.write("                208,Amar Neptune baner Pune 411045 <br>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <strong>Phone:</strong>+91 9834742691<br>\r\n");
      out.write("                <strong>Email:</strong> info@pandd.in<br>\r\n");
      out.write("              </p>\r\n");
      out.write("              <div class=\"social-links mt-3\">\r\n");
      out.write("                <a href=\"https://twitter.com/CAPANDD\" class=\"twitter\"><i class=\"bx bxl-twitter\"></i></a>\r\n");
      out.write("                <a href=\"https://www.facebook.com/capandd\" class=\"facebook\"><i class=\"bx bxl-facebook\"></i></a>\r\n");
      out.write("                \r\n");
      out.write("                <a href=\"https://www.youtube.com/channel/UCzmlQfqLNmY9PI2lMabuaVA\" class=\"google-plus\"><i class=\"bx bxl-youtube\"></i></a>\r\n");
      out.write("                <a href=\"https://www.linkedin.com/company/54317819\" class=\"linkedin\"><i class=\"bx bxl-linkedin\"></i></a>\r\n");
      out.write("                <a href=\"https://wa.me/919834742691?text=I%20would%20like%20to%20have%20your%20servies\" class=\"google-plus\"><i class=\"bx bxl-whatsapp\"></i></a>\r\n");
      out.write("\r\n");
      out.write("                <a href=\"https://t.me/PUSEGAONKARANDDINDOKAR\" class=\"google-plus\" style=\"margin-top: 5px\"><i class=\"bx bxl-telegram\"></i></a>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-2 col-md-6 footer-links\">\r\n");
      out.write("            <h4>Useful Links</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"about.html\">About us</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Services</a></li>\r\n");
      out.write("              \r\n");
      out.write("\r\n");
      out.write("             <li><i class=\"bx bx-chevron-right\"></i><a href=\"VideoBlog.jsp\">Video Blogs</a></li>\r\n");
      out.write("            <li><i class=\"bx bx-chevron-right\"></i><a href=\"photo_blog.jsp\">Photo Blogs</a></li>\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"#\">Links & Updates</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-3 col-md-6 footer-links\">\r\n");
      out.write("            <h4>Our Services</h4>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Audit & Assurance</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Direct & Indirect Taxes</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Banking & Finance</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Business and Knowledge Process Outsourcing and Accounting</a></li>\r\n");
      out.write("              <li><i class=\"bx bx-chevron-right\"></i> <a href=\"services.html\">Corporate Law</a></li>\r\n");
      out.write("           \r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"col-lg-4 col-md-6 footer-newsletter\">\r\n");
      out.write("            <h4><a href=\"https://www.youtube.com/channel/UCzmlQfqLNmY9PI2lMabuaVA\">Our Youtube Channel</a></h4>\r\n");
      out.write("            <p></p>\r\n");
      out.write("            <form action=\"\" method=\"post\">\r\n");
      out.write("              <a href=\"https://www.youtube.com/channel/UCzmlQfqLNmY9PI2lMabuaVA\"><input type=\"email\" name=\"email\"><input type=\"submit\" value=\"Subscribe\"></a>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </footer><!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"icofont-simple-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/jquery.easing/jquery.easing.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/venobox/venobox.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/waypoints/jquery.waypoints.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/owl.carousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
